name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Package Spring Boot App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package

      - name: List JAR files
        run: ls -la target/

      - name: Archive JAR
        uses: actions/upload-artifact@v4
        with:
          name: springboot-app
          path: target/*.jar
          if-no-files-found: error
          retention-days: 1

  deploy:
    name: Deploy Job
    needs: build
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Echo Deploy
        run: echo "🚀 Deploy step started"

      - name: logs
        run: echo "✅ Reached logs step at the end of deploy job"
